package login.domain;



import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class Wishlist {

    private String listName;
    private String description;
    private int id; // just used to demo retrieval of autogenerated key in UserMapper

    public Wishlist(String listName, String description) {
        this.listName = listName;
        this.description = description;

    }



    public String getListName() {
        return listName;
    }

    public void setListName(String listName) {
        this.listName = listName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
